services:
  api:
    build: .
    container_name: zone_api
    restart: always
    user: rodion
    depends_on:
      - postgres
    command: ["pipenv", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env

  postgres:
    image: postgres:15-alpine
    container_name: zone_postgres
    user: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
