# Generated by Django 5.1.6 on 2025-02-17 15:25

import apps.url_management.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('redirect_url', models.URLField(verbose_name='Redirect URL')),
                ('is_private', models.BooleanField(default=False, verbose_name='Is Private')),
                ('redirect_identifier', models.CharField(default=apps.url_management.utils.generate_redirect_identifier, editable=False, max_length=100, unique=True, verbose_name='Redirect Identifier')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Redirect Rule',
                'verbose_name_plural': 'Redirect Rules',
                'ordering': ['-created'],
            },
        ),
    ]
